/**
 * Generates supabase/seed.sql from the original static data files.
 *
 * The Figma export shipped its content as TypeScript literals. Rather than
 * transcribing that prose into SQL by hand (and drifting from it), we read
 * the real modules and emit the insert statements.
 *
 *   node scripts/generate-seed.mjs
 *
 * Node >= 22.6 strips the type annotations natively.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// pathToFileURL: a bare Windows path ("C:\...") is not a valid ESM specifier.
const load = (rel) => import(pathToFileURL(path.join(root, rel)).href);

const { puppies } = await load("src/data/puppies.ts");
const { guides } = await load("src/data/guides.ts");

/** Quote a value as a Postgres literal. */
const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
/** Quote a JS value as a jsonb literal. */
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
/** Quote a string[] as a Postgres text[] literal. */
const arr = (items) =>
  items.length === 0
    ? "'{}'::text[]"
    : `array[${items.map(q).join(", ")}]::text[]`;

// ---------------------------------------------------------------------
// Photography guard
//
// A photograph on two listings means a visitor comparing two puppies is
// shown the same dog twice, which on an adoption site reads as a fake
// listing. It is easy to reintroduce by copying a seed block, and easy to
// miss by eye across fifteen puppies — so fail the build instead.
// ---------------------------------------------------------------------
const seenPhoto = new Map(); // url -> puppy name
const photoClashes = [];
for (const p of puppies) {
  if (p.photos.length === 0) photoClashes.push(`${p.name} has no photograph`);
  for (const url of p.photos) {
    const owner = seenPhoto.get(url);
    if (owner) photoClashes.push(`${p.name} reuses ${owner}'s photograph: ${url}`);
    else seenPhoto.set(url, p.name);
  }
}
if (photoClashes.length) {
  // Thrown rather than process.exit()d: exiting while stdout is still
  // draining trips a libuv assertion on Windows and buries the message.
  for (const line of photoClashes) console.error(`  ${line}`);
  throw new Error(
    `Photography check failed - ${photoClashes.length} problem(s) listed above.`
  );
}
console.log(`Photography: ${seenPhoto.size} distinct images across ${puppies.length} puppies.`);

const out = [];
const w = (line = "") => out.push(line);

w("-- =====================================================================");
w("-- Yorkshire Adoption Home - seed data");
w("-- =====================================================================");
w("-- GENERATED by scripts/generate-seed.mjs - do not edit by hand.");
w("-- Idempotent: safe to run more than once.");
w("-- =====================================================================");
w();
w("begin;");
w();

// ---------------------------------------------------------------------
// Parents
// ---------------------------------------------------------------------
const parentMap = new Map(); // "name|role" -> healthTests
for (const p of puppies) {
  parentMap.set(`${p.parents.sire.name}|sire`, p.parents.sire.healthTests);
  parentMap.set(`${p.parents.dam.name}|dam`, p.parents.dam.healthTests);
}

w("-- Parents ------------------------------------------------------------");
w("insert into public.parents (name, role, health_tests) values");
w(
  [...parentMap.entries()]
    .map(([key, tests]) => {
      const [name, role] = key.split("|");
      return `  (${q(name)}, ${q(role)}::parent_role, ${j(tests)})`;
    })
    .join(",\n") + ""
);
w("on conflict (name, role) do update set health_tests = excluded.health_tests;");
w();

// ---------------------------------------------------------------------
// Puppies
// ---------------------------------------------------------------------
w("-- Puppies ------------------------------------------------------------");
puppies.forEach((p, i) => {
  w(`insert into public.puppies (`);
  w(`  slug, name, sex, date_of_birth, status, temperament_tags,`);
  w(`  temperament_notes, photos, display_order, sire_id, dam_id`);
  w(`) values (`);
  w(`  ${q(p.slug)}, ${q(p.name)}, ${q(p.sex)}::puppy_sex, ${q(p.dateOfBirth)}::date,`);
  w(`  ${q(p.status)}::puppy_status, ${arr(p.temperamentTags)},`);
  w(`  ${q(p.temperamentNotes)},`);
  w(`  ${arr(p.photos)}, ${i},`);
  w(`  (select id from public.parents where name = ${q(p.parents.sire.name)} and role = 'sire'),`);
  w(`  (select id from public.parents where name = ${q(p.parents.dam.name)} and role = 'dam')`);
  w(`)`);
  w(`on conflict (slug) do update set`);
  w(`  name = excluded.name, sex = excluded.sex, date_of_birth = excluded.date_of_birth,`);
  w(`  status = excluded.status, temperament_tags = excluded.temperament_tags,`);
  w(`  temperament_notes = excluded.temperament_notes, photos = excluded.photos,`);
  w(`  sire_id = excluded.sire_id, dam_id = excluded.dam_id;`);
  w();

  // Health records are replaced wholesale so re-seeding never duplicates.
  w(
    `delete from public.puppy_vaccinations where puppy_id = (select id from public.puppies where slug = ${q(p.slug)});`
  );
  if (p.vaccinations.length) {
    w(`insert into public.puppy_vaccinations (puppy_id, name, administered, due, done, display_order) values`);
    w(
      p.vaccinations
        .map(
          (v, vi) =>
            `  ((select id from public.puppies where slug = ${q(p.slug)}), ${q(v.name)}, ${q(v.date)}::date, ${v.due ? `${q(v.due)}::date` : "null"}, ${v.done}, ${vi})`
        )
        .join(",\n") + ";"
    );
  }
  w();

  w(
    `delete from public.puppy_dewormings where puppy_id = (select id from public.puppies where slug = ${q(p.slug)});`
  );
  if (p.dewormings.length) {
    w(`insert into public.puppy_dewormings (puppy_id, product, administered, display_order) values`);
    w(
      p.dewormings
        .map(
          (d, di) =>
            `  ((select id from public.puppies where slug = ${q(p.slug)}), ${q(d.product)}, ${q(d.date)}::date, ${di})`
        )
        .join(",\n") + ";"
    );
  }
  w();
});

// ---------------------------------------------------------------------
// Guides
// ---------------------------------------------------------------------
w("-- Guides -------------------------------------------------------------");
w("insert into public.guides (slug, title, summary, reading_time_min, published_date, sections, display_order) values");
w(
  guides
    .map(
      (g, i) =>
        `  (${q(g.slug)}, ${q(g.title)}, ${q(g.summary)}, ${g.readingTimeMin}, ${q(g.publishedDate)}::date, ${j(g.sections)}, ${i})`
    )
    .join(",\n") + ""
);
w("on conflict (slug) do update set");
w("  title = excluded.title, summary = excluded.summary,");
w("  reading_time_min = excluded.reading_time_min,");
w("  published_date = excluded.published_date, sections = excluded.sections;");
w();

// ---------------------------------------------------------------------
// Site settings
// ---------------------------------------------------------------------
const settings = [
  ["site_name", "Yorkshire Adoption Home", true],
  ["tagline", "A small, selective Yorkshire Terrier breeder. One or two litters a year, raised in our kitchen.", true],
  ["contact_email", "hello@yorkshire-adoption.example", true],
  ["whatsapp_number", "447700900000", true],
  ["applications_open", true, true],
  ["messenger_enabled", true, true],
  ["messenger_greeting", "Hello. Ask us anything about our Yorkshire Terriers or the adoption process - we usually reply within a day.", true],
  ["messenger_away_message", "We are not at the desk right now. Leave a message and your email, and we will come back to you.", true],
  ["office_hours", "Mon-Sat, 9am - 6pm (GMT+8)", true],
  ["review_sla_days", 14, true],
  ["notify_email", "hello@yorkshire-adoption.example", false],
];

w("-- Site settings ------------------------------------------------------");
w("insert into public.site_settings (key, value, is_public) values");
w(
  settings
    .map(([key, value, isPublic]) => `  (${q(key)}, ${j(value)}, ${isPublic})`)
    .join(",\n") + ""
);
w("on conflict (key) do nothing;");
w();
w("commit;");
w();

writeFileSync(path.join(root, "supabase/seed.sql"), out.join("\n"), "utf8");
console.log(
  `Wrote supabase/seed.sql - ${puppies.length} puppies, ${parentMap.size} parents, ${guides.length} guides, ${settings.length} settings.`
);
